var oPrintData = {
"DATA":{"@id" : "Print", "@stream" : "true", "@time" : "0", "@dur" : "380528", "@type" : "Image", 
"PREL-ITEMS": [ 
{"@src" : "Print1.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print10.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print11.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print12.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print13.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print14.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print15.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print2.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print3.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print4.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print5.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print6.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print7.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print8.jpeg", "@type" : "Image", "@fmt" : "JPEG" }, 
{"@src" : "Print9.jpeg", "@type" : "Image", "@fmt" : "JPEG" }
 ], 
"SGMTS": [ 
{"@inx" : "1", "@type" : "Image", "@fmt" : "PNG", "@time" : "0", "@dur" : "380528", 
"SMPLS": [ 
{"@inx" : "1", "@time" : "0", "@dur" : "9054", "@src" : "Print1.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "The Life and Works of Marie Curie  The Discovery of Radioactivity, Polonium, and Radium" }, 
{"@inx" : "2", "@time" : "9054", "@dur" : "36055", "@src" : "Print2.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Biography: Childhood in Poland" }, 
{"@inx" : "3", "@time" : "45109", "@dur" : "51060", "@src" : "Print3.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Biography: Life in France" }, 
{"@inx" : "4", "@time" : "96169", "@dur" : "39054", "@src" : "Print4.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Background to Curie’s Work" }, 
{"@inx" : "5", "@time" : "135223", "@dur" : "21043", "@src" : "Print5.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Scientific Discoveries:   Radioactivity of Thorium" }, 
{"@inx" : "6", "@time" : "156266", "@dur" : "9044", "@src" : "Print6.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Scientific Discoveries: Polonium" }, 
{"@inx" : "7", "@time" : "165310", "@dur" : "6056", "@src" : "Print7.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Scientific Discoveries: Radium" }, 
{"@inx" : "8", "@time" : "171366", "@dur" : "30062", "@src" : "Print8.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Proving Polonium & Radium Existed" }, 
{"@inx" : "9", "@time" : "201428", "@dur" : "27064", "@src" : "Print9.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Historical Context: World War I" }, 
{"@inx" : "10", "@time" : "228492", "@dur" : "27074", "@src" : "Print10.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Historical Context: Postwar" }, 
{"@inx" : "11", "@time" : "255566", "@dur" : "42063", "@src" : "Print11.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Death from Radiation" }, 
{"@inx" : "12", "@time" : "297629", "@dur" : "18044", "@src" : "Print12.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Awards and Honors" }, 
{"@inx" : "13", "@time" : "315673", "@dur" : "33048", "@src" : "Print13.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Curie’s Contribution and Legacy" }, 
{"@inx" : "14", "@time" : "348721", "@dur" : "21043", "@src" : "Print14.jpeg", "@width" : "640", "@height" : "400", "@fmt" : "JPEG", 
"@text" : "Applications" }, 
{"@inx" : "15", "@time" : "369764", "@dur" : "10764", "@src" : "Print15.jpeg", "@width" : "640", "@height" : "400", "@poi" : "370765", "@fmt" : "JPEG", 
"@text" : "Famous Quotes" }
 ] }
 ] }}